language: node_js
node_js: stable

script:
  - npm run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: storybook-static
  target_branch: gh-pages
  on:
    branch: master